### ISSUE TITLE
[Feature Request]: Add support for Flow Matching SDXL Models

### ISSUE THREAD

**Issue by GumGum10** [Panchovix/stable-diffusion-webui-reForge#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Hi, appreciate the hard work on this! 
There's a new SDXL model trained using Flow Matching:
https://huggingface.co/nyanko7/nyaflow-xl-alpha

Currently, given the ComfyUI workflow provided in the repo, the model works in Comfy. However when trying to inference with it in reforge, the output is just random noise. 

The only thing different from any other normal gen in the ComfyUI workflow is the presence of the ModelSamplingSD3 Shift node, so hoping for an easy fix/change to make it compatible with reforge.

### Proposed workflow

1. Add Model Sampling SD3 shift equivalent in the Gradio UI
2. Upon inference, the random noise issue is resolved

**Comment by Panchovix** [comment]
It should be working as for now on dev/dev2/exp branches

![image](https://github.com/user-attachments/assets/8dba4b03-7f18-4c04-be2d-677f0e4a04a3)

I downloaded the model and tested there, seems to work.

For main branch is a bit harder because it has to be backported.

Here is an example of it working

![image](https://github.com/user-attachments/assets/51ca24ab-c33f-4aef-a561-a0d6c2ea0c0e)

It seems a bit noisy, but I guess it depends of parameters and such. Also it seems to work only with comfy samplers.

**Comment by alefh123** [comment]
You're a legend!! Thanks so much, seems to work best with @cfg 9, rescale 0.7 with either Euler or Heun Comfy and Karras or KL Optimal:
![image](https://github.com/user-attachments/assets/f9bb3bef-40a2-497e-b862-ad24ccb0b0c3)
