### ISSUE TITLE
[Feature Request]: Implement Hi-Diffusion

### ISSUE THREAD

**Issue by CasualDev242** [Panchovix/stable-diffusion-webui-reForge#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Hi-Diffusion allows SDXL checkpoints to generate much larger images, like 2k-4k, without the need for any type of Hi-Res fix. The original implementation can be found here:  https://github.com/megvii-research/HiDiffusion , and here are two example implementations for ComfyUI: 1) https://github.com/blepping/comfyui_jankhidiffusion/tree/main and 2) https://github.com/florestefano1975/ComfyUI-HiDiffusion

### Proposed workflow

1. Go to img-to-img or txt-to-img-tab
2. Select the Hi-Diffusion UI element selection
3. Check "Enable
4. Now you can generate much larger image sizes in the interfaces existing Width and Height scales
5. Profit

**Comment by Panchovix** [comment]
Added some commits related to it

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/37471b59384e3a7f66ecd917f2dab6bfaffbcd42

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/19812e53c5016698af083ae66eb783c2eaaf0d22

Not sure what I'm exactly doing, but it seems it does generate?

**Comment by Panchovix** [comment]
To add, this works ONLY on dev_upstream branch. Main branch doesn't work because it is missing comfy upstream changes to make it work.

Since main is only a1111 upstream changes, it is disabled there.

**Comment by Panchovix** [comment]
Ohh so they are meant to be used together? That explain things! If you can take a look, it would be amazing. Honestly, just ported the code to Forge haha

**Comment by Panchovix** [comment]
Okay, implementation is complete now!

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/dc07afe83193f3228d0c0b55331a09e1744843bb

It took a lot but it should work as expected, added a lot of explanations and also the simple nodes into gradio tabs lol.

Let me know how it works for you!

**Comment by ivaxsirc** [comment]
There are an upscaler that is mind-blowing but requires a lot of VRAM, it's SUPIR, Nobody has made extensions for a1111 or forge, I suppose due to the difficulty of implementation, but incorporating SUPIR into Reforge would be a before and after, i think that many people do a ko-fi if you implemented, i'm the first

Thanks
https://github.com/Fanghua-Yu/SUPIR

**Comment by Panchovix** [comment]
@ivaxsirc that sounds very interesting, gonna check it out!

**Comment by Panchovix** [comment]
Hi there, don't worry. If it doesn't work as intended we can just have it disabled or not use it, but some people have been using it and removing it would case issues for them.

And don't worry, I will wait at how you can do the extension. There is the other implementation but it's harder to port it.

Even then, most extensions from comfy would work on reforge, since it's the same backend, but the script for gradio and applying the changes is the important part.

Also, gonna check out StableSR. Is this on comfy as well?
