### ISSUE TITLE
[Bug]: lora browser is broken after latest updates

### ISSUE THREAD

**Issue by Hugs288** [Panchovix/stable-diffusion-webui-reForge#73]
### Checklist

- [X] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

lora browser now looks like this
![image](https://github.com/user-attachments/assets/e441f644-5f6c-45cd-bbf9-63db1baee141)
icons are gone, tree view is also gone, and i cant scroll.

### Steps to reproduce the problem

launch webui
browse lora

### What should have happened?

lora browser should work properly as it did before

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-07-27-15-26.json](https://github.com/user-attachments/files/16400684/sysinfo-2024-07-27-15-26.json)

### Console logs

```Shell
-
```

### Additional information

-

**Comment by nveaa1** [comment]
I am also encountering an unscrollable Lora browser in both mobile and desktop views. It seems that something in either commit 9aac257 and/or b433397 may have broken the Lora viewer in some way.

**Comment by VcCart** [comment]
Checkpoint browser, Hypernetworks, etc broke too.
Сломалось форматирование кнопок управления:
![2024-07-27_234616](https://github.com/user-attachments/assets/4714a7d1-e000-4681-9f64-ea2455f103c2)
The scroll bar also doesn't work in model control blocks.

**Comment by Panchovix** [comment]
Thanks for the report. For now, gonna revert latest commit related to those views.

**Comment by Panchovix** [comment]
Okay after the revert, it works fine. Even then, I'm gonna try to bring some upstream changes related to the lora view and keep the actual tree view. This is because the performance difference between the old and new version is a lot if having ton of loras.

**Comment by Panchovix** [comment]
By the way, as I said in the previous comment, I the tree view correctly and also the new dir view. It fixes the bugs found and also is way faster than before.

Remember to set the view depending of how do you like it. This is dir view

![imagen](https://github.com/user-attachments/assets/dedce219-2117-41f6-9dc4-fdf3cd842617)

And this is tree view (by default)

![imagen](https://github.com/user-attachments/assets/6bf0d389-210c-4756-82eb-8152a6aff738)

**Comment by ali0une** [comment]
Hi there.

Also the LoRA displayed should match the currently selected model but it displays all LoRA.

Like i have a whatever.safetensors with a corresponding whatever.json generated in A1111/Forge/reForge that looks like :

```
{
    "description": "",
    "sd version": "SD1",
    "activation text": "",
    "preferred weight": 0,
    "notes": ""
}
```

As you can see the line  "sd version": "SD1" tells it's a SD1 model, it would be  "sd version": "SDXL" for a SDXL model

in A1111/Forge this is taked care of, but not in reForge who displays ALL LoRA instead of just SD1 or SDXL ones depending on the currently selected model.

**Comment by Panchovix** [comment]
Hi there @ali0une, thanks for the report. Will have to check out how to handle this, I think on Forge it works because an older version patched for it was done (but it would break new dir view and sorting options), and A1111 gets the model info by the A1111 backend itself.

Wondering, does this affect the output or LoRA don't work as expected?

Thanks for the report!

**Comment by ali0une** [comment]
@Panchovix thnxX!

i looked again, in the latest Forge it's the same.
LoRA are displayed right as expected.

Edited my post above accordingly.

**Comment by Panchovix** [comment]
@ali0une I pushed a new commit that maybe adress this, can you check?

**Comment by ali0une** [comment]
Many thanks @Panchovix works perfect!

Keep up the good work ...
